/**
 * PeakAware API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiSentieriIdToggleVisibilitaPatch200Response { 
    successo?: boolean;
    isVisible?: boolean;
    message?: string;
}

