/**
 * PeakAware API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metadati del sentiero recuperati da OSM
 */
export interface SentieroProperties { 
    /**
     * Nome ufficiale del sentiero
     */
    name?: string;
    /**
     * Riferimento numerico (es. SAT 401)
     */
    ref?: string;
    /**
     * Grado di difficoltà tecnica
     */
    difficulty?: string;
    /**
     * Descrizione dettagliata del percorso
     */
    description?: string;
    /**
     * Dislivello positivo del sentiero
     */
    dislivello_positivo?: number;
    /**
     * Tempo stimato di percorrenza in ore
     */
    tempoAndata?: number;
    /**
     * Tempo stimato di ritorno in ore
     */
    tempoRitorno?: number;
    /**
     * Lunghezza del sentiero in km
     */
    lunghezza?: number;
}

