/**
 * PeakAware API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SentieroGeometry } from './sentieroGeometry';
import { SentieroProperties } from './sentieroProperties';


export interface Sentiero { 
    /**
     * Identificativo univoco di OpenStreetMap
     */
    osm_id: string;
    /**
     * Gestisce la visibilità del sentiero nella mappa
     */
    isVisible?: boolean;
    properties?: SentieroProperties;
    geometry: SentieroGeometry;
    createdAt?: string;
    updatedAt?: string;
}

