/**
 * PeakAware API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SentieroGeometry } from './sentieroGeometry';


export interface Sentiero { 
    osm_id: string;
    isVisible?: boolean;
    /**
     * Tutti i tag OSM del sentiero (schema libero)
     */
    properties?: { [key: string]: any; };
    /**
     * Lunghezza calcolata in km
     */
    lunghezza?: number;
    /**
     * Dislivello positivo in metri
     */
    dislivello_positivo?: number;
    /**
     * Tempo stimato andata in ore
     */
    tempoAndata?: number;
    /**
     * Tempo stimato ritorno in ore
     */
    tempoRitorno?: number;
    difficolta?: string;
    geometry: SentieroGeometry;
}

