/**
 * PeakAware API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dati GeoJSON del tracciato
 */
export interface SentieroGeometry { 
    type?: SentieroGeometry.TypeEnum;
    coordinates?: Array<Array<number>>;
}
export namespace SentieroGeometry {
    export const TypeEnum = {
        LineString: 'LineString',
        MultiLineString: 'MultiLineString'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


